version: "3"
services:
    # db:
    #     container_name: "db"
    #     build: ./docker/mysql
    #     restart: always
    #     tty: true
    #     environment:
    #       MYSQL_DATABASE: ${DATABASE_DB}
    #       MYSQL_USER: ${DATABASE_USER}
    #       MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    #       MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    #     ports:
    #       - "${DATABASE_PORT}:${DATABASE_PORT}"
    #     volumes:
    #       # - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    #       - ./docker/mysql/conf.d:/etc/mysql/conf.d
    #       # - ./log/mysql:/var/log/mysql
    #     networks:
    #       - local-net
    db:
      image: mysql:8
      container_name: db
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
        - MYSQL_DATABASE=${DATABASE_DB}
      command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']
      ports:
        - "${DATABASE_PORT}:${DATABASE_PORT}"
      volumes:
        - "db-data:/var/lib/mysql"
        - ./docker/mysql/conf.d:/etc/mysql/conf.d
      networks:
        - local-net
  
    gin-atomy-platform:
        container_name: gin-atomy-platform
        build: ./docker/api
        restart: always
        depends_on:
          - db
        links:
          - db
        environment:
          - SERVER_PORT=${SERVER_PORT}
          - DATABASE_HOST=${DATABASE_HOST}
          - DATABASE_PORT=${DATABASE_PORT}
          - DATABASE_USER=${DATABASE_USER}
          - DATABASE_PASSWORD=${DATABASE_PASSWORD}
          - DATABASE_DB=${DATABASE_DB}
        ports:
          - "${SERVER_PORT}:${SERVER_PORT}"
        networks:
          - local-net

networks:
  local-net:
      driver: bridge
volumes:
  db-data:
        
